# Generated by Django 3.0.6 on 2020-05-16 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Latest News', max_length=100, unique='True', validators=[django.core.validators.MinLengthValidator(limit_value=10, message='News description should be atleast 10 chars'), django.core.validators.MaxLengthValidator(limit_value=100, message='News description can not be > 100 chars')], verbose_name='news')),
                ('arrival_date', models.DateField(auto_now_add=True)),
                ('expired', models.BooleanField(db_column='News Expired', default=False, help_text='Has this news expired')),
                ('expire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the product', max_length=50, verbose_name='product Name')),
                ('details', models.CharField(help_text='Details of the product', max_length=50, null=True, verbose_name='Product Detail')),
                ('cost', models.FloatField(help_text='Product cost per unit', verbose_name='Product Cost')),
                ('discount_type', models.CharField(choices=[('PR', 'PR'), ('Amt', 'Amt')], help_text='Discount on this product e.g Amount, Percent', max_length=3, verbose_name='Discount Type')),
                ('discount', models.FloatField(default=0.0, help_text='Discount of for the product in amount', verbose_name='Discount Price')),
                ('percent', models.FloatField(default=0.0, help_text='Discount of for the product in percent', verbose_name='Discount Percent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
